### ISSUE TITLE
ERROR: Sync of gutbackup: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by gutenye** [seblu/archversion#1]
```
$ archversion --debug sync
DEBUG: loading config file at: /home/guten/.config/archversion/packages.conf
DEBUG: Loading database /home/guten/.cache/archversion/packages.cache
DEBUG: Syncing versions of package gutbackup
DEBUG: Get upstream version
ERROR: Sync of gutbackup: float() argument must be a string or a number, not 'NoneType'
DEBUG: Saving database /home/guten/.cache/archversion/packages.cache
```

**Comment by gutenye** [comment]
I found the error at https://github.com/seblu/archversion/blob/master/src/lib/archversion/version.py#L92 
I did not define a timeout variable, so it went wrong.

**Comment by gutenye** [comment]
@seblu This is a very great tool, I want to check update and upload new version to https://aur.archlinux.org in one-step, how do you manage the last part (upload to aur website)?

**Comment by seblu** [comment]
fixed in https://github.com/seblu/archversion/commit/aceddd986a3dcd5d9bc07c9f51e93900be8ceb7a

I have usualy do something like this:
archversion update -c
makepkg -S
burp pkg.src.tar.gz

**Comment by gutenye** [comment]
Thanks, I'm working on a project to make everything automation.
